### ISSUE TITLE
Custom episodes number

### ISSUE THREAD

**Issue by Knocks83** [NicoAiko/mikazuki#168]
For example: Pocket Monsters Sun & Moon episode 7 is Pocket Monsters episode 952 so it would be cool to have, instead of episode 7 on 146 episodes, episode 952 on 1091 (server-side or client-side with cookies, worst is you have to set it for all devices, not really a problem)

**Comment by NicoAiko** [comment]
I've been thinking about this feature for some time since you posted it.

What this feature would mean is that e.g. all Pocket Monsters Seasons would merge into one element that only exists on client-side. The client would have to calculate the progress you enter and update the separate items server-side.

I'll have some more thoughts about this, as there are some questions to be cleared.

- What happens, if you have unfinished prequels and you enter a progress that would "complete" that prequel?
- How to handle the amount of episodes that are countable until the latest sequel? (still `???` or `XXX+`?)
- How to display each season separately on Detail page?
- Ability to update single seasons separately

**Comment by Knocks83** [comment]
It wouldn't be merging them, it's just a graphical thing, you set a number (positive or negative) and it does episode + the number you set.

**Comment by NicoAiko** [comment]
That doesn't seem that logical to me.
You shouldn't be updating a sequel to episode 900 when it's actually episode 7.
It seems more logical and consistent to me if you would edit "Pocket Monsters" as a whole.

**Comment by NicoAiko** [comment]
This request won't be implemented here, as working with values that (in this case) AniList doesn't support, can lead to errors.

It's too easy to do mistakes here.
